server:
  port: 9191

spring:
  application:
    name: 'API-GATEWAY'
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTAMENT-SERVICE
          uri: lb://DEPARTAMENT-SERVICE
          predicates:
              - Path=/departament/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost