server:
  port: 9191

spring:
  application:
    name: 'API-GATEWAY'
  cloud:
    gateway:
      routes:
        - id: REST-SERVICE
          uri: lb://REST-SERVICE
          predicates:
            - Path=/api/users**
        - id: DB-SERVICE
          uri: lb://DB-SERVICE
          predicates:
              - Path=/api/user**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost