server:
  port: 9191

spring:
  application:
    name: 'API-GATEWAY'
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
            - Method=GET,POST
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackuri: forward:/fallback/userServiceFallback
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
            - Method=GET,POST
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackuri: forward:/fallback/orderServiceFallback

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost