application_id: cloud

jwt:
  secret: newSecret
  issuer: API-GATEWAY
  expiration-time: 604800000

  #rabbitMQ connection
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${application_id:0}:${random.value}