server:
  port: 8012

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kpuda/SpringCloudConfigRepo
          username: kpuda
          password: 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
          clone-on-start: true
          default-label: main

