server:
  port: 8012

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kpuda/SpringCloudConfigRepo
          username: kpuda
          password: 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
          clone-on-start: true
          default-label: main
  #rabbitMQ connection
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#enabling 'refresh config' endpoint
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

#TODO rabbitmq default url localhost:15672