server:
  port: 8012

spring:
  application:
    name: cloudConfig
  profiles:
    active: native # native for file systems, git for remote repo.
  cloud:
    config:
      server:
        native: # we set native if we want to use native files system
          search-locations: file:\${user.dir}\SpringCloud\cloud-properties\
#        git: #we set git if we want to download properties from remote repo.
#          uri: https://github.com/kpuda/SpringCloudConfigRepo
#          username: kpuda
#          password: tbd #this password is unused
#          clone-on-start: true
#          default-label: main

  #rabbitMQ connection
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#enabling 'refresh config' endpoint
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

#TODO rabbitmq default url localhost:15672