server:
  port: ${PORT:0}
spring:
  application:
    name: users-ms
  devtools:
    restart:
      enabled: false
  #CONFIG SERVER
  config:
    import: optional:configserver:http://localhost:8012
  profiles:
    active: users-ms

    #application_id is spring boot run arg
    #mvn spring-boot:run -Dspring-boot.run.arguments=--application_id=xd

management:
  endpoints:
    web:
      exposure:
        include: beans, health, routes, httptrace, mappings #todo why doesnt it work

logging:
  level:
    com.kp.users.microservice.service.AlbumsServiceClient: DEBUG