application_id: users-ms

spring:
  #DB
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_db
    username: root
    password: root
#    driverClassName: org.h2.Driver
  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update # todo jce java cryptography extension
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true

