application_id: users-ms

spring:
  #DB
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_db
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update # todo jce java cryptography extension

#Logging feign client in debug mode
logging:
  level:
    com.kp.users.microservice.service.AlbumsServiceClient: DEBUG

